export const MODULE_TYPES = {
  UNCATEGORIZED: "UNCATEGORIZED",
  AUTH: "AUTH",
  ENROLLMENTS: "ENROLLMENTS",
  SCHEDULES: "SCHEDULES",
  GRADING: "GRADING",
  DOCUMENTS: "DOCUMENTS",
  PAYMENTS: "PAYMENTS",
  REPORTS: "REPORTS",
  CONTENTS: "CONTENTS",
  SYSTEM: "SYSTEM",
};
